version: '3.8'

services:
  app:
    container_name: cloud_drive
    build: .
    ports: 
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - fullstack

  postgres:
    image: postgres:latest
    container_name: cloud_drive_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  app:
  database_postgres:

networks:
  fullstack:
    driver: bridge